# Generated by Django 5.0.1 on 2024-02-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=200)),
                ('habilitado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tb_servicos',
            },
        ),
    ]
