# Generated by Django 5.0.1 on 2024-02-25 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicial', models.DateTimeField()),
                ('data_hora_final', models.DateTimeField()),
                ('servico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.servico')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_agendamentos',
            },
        ),
    ]
