# Generated by Django 5.0.1 on 2024-02-25 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_agenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusAgendamento',
            fields=[
                ('agenda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='agenda.agenda')),
                ('status', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tb_status_agendamentos',
            },
        ),
    ]
