"""empty message

Revision ID: 0059d817ae7d
Revises: 491744790627
Create Date: 2023-12-03 17:03:57.179050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0059d817ae7d'
down_revision: Union[str, None] = '491744790627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_postagens', sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('tb_postagens', sa.Column('alterado_em', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_postagens', 'alterado_em')
    op.drop_column('tb_postagens', 'criado_em')
    # ### end Alembic commands ###
