"""Criadas as colunas criado_em e atualizado_em na tabela tb_usuarios

Revision ID: 2ae1f853b8a5
Revises: 
Create Date: 2023-12-03 15:24:55.297665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ae1f853b8a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_usuarios', sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('tb_usuarios', sa.Column('atualizado_em', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_usuarios', 'atualizado_em')
    op.drop_column('tb_usuarios', 'criado_em')
    # ### end Alembic commands ###
