"""empty message

Revision ID: 491744790627
Revises: ca2997b3864b
Create Date: 2023-12-03 17:02:41.832850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '491744790627'
down_revision: Union[str, None] = 'ca2997b3864b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_perfis', sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('tb_perfis', sa.Column('alterado_em', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_perfis', 'alterado_em')
    op.drop_column('tb_perfis', 'criado_em')
    # ### end Alembic commands ###
