"""empty message

Revision ID: 5bf611beb7a7
Revises: 0059d817ae7d
Create Date: 2023-12-03 17:12:45.638038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bf611beb7a7'
down_revision: Union[str, None] = '0059d817ae7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_comentarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('postagem_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=200), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('alterado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['postagem_id'], ['tb_postagens.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['tb_usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_comentarios')
    # ### end Alembic commands ###
