# Generated by Django 5.0.1 on 2024-02-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_statusagendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusagendamento',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
