# Generated by Django 5.0 on 2023-12-17 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='opcao',
            table='tb_opcoes',
        ),
        migrations.AlterModelTable(
            name='pergunta',
            table='tb_perguntas',
        ),
    ]
