"""criada model perfil

Revision ID: 82692c7156f9
Revises: 77a3c872ee7b
Create Date: 2023-12-10 14:57:52.644575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82692c7156f9'
down_revision: Union[str, None] = '77a3c872ee7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_perfis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('sobrenome', sa.String(length=200), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('data_de_nascimento', sa.DateTime(), nullable=True),
    sa.Column('genero', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['tb_usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_perfis')
    # ### end Alembic commands ###
