"""criada model pedido

Revision ID: 8d7301f8f025
Revises: 6622356f0634
Create Date: 2023-12-10 15:54:29.251186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d7301f8f025'
down_revision: Union[str, None] = '6622356f0634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_pedidos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data_do_pedido', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['tb_usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_pedidos')
    # ### end Alembic commands ###
