# Generated by Django 5.0.1 on 2024-01-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rodada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(null=True)),
                ('ano', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'tb_rodadas',
            },
        ),
    ]
