# Generated by Django 5.0.1 on 2024-01-21 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0002_rodada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gols_clube_mandante', models.IntegerField(default=0)),
                ('gols_clube_visitante', models.IntegerField(default=0)),
                ('estadio', models.CharField(blank=True, max_length=200, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('clube_mandante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clube_mandante', to='dados.clube')),
                ('clube_visitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clube_visitante', to='dados.clube')),
                ('rodada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dados.rodada')),
            ],
            options={
                'db_table': 'tb_partidas',
            },
        ),
    ]
