# Generated by Django 5.0.1 on 2024-01-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0003_partida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='data',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='hora',
        ),
        migrations.AddField(
            model_name='partida',
            name='data_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
